#!/usr/bin/env python3
"""
Merge local OS skills with external skill registry.

This script scans both:
1. External skills (from gentle-ai registry)
2. Local OS skills (from 01_Personal_Os/01_Core/02_Tools/02_Skills/)

And generates a unified skill-registry.md
"""

import os
import re
from pathlib import Path
from datetime import datetime

# Paths - use absolute path to project root
OS_ROOT = Path(r"C:\Users\sebas\Desktop\Think_Different")
LOCAL_SKILLS_DIR = OS_ROOT / "01_Personal_Os" / "01_Core" / "02_Tools" / "02_Skills"
REGISTRY_FILE = OS_ROOT / ".atl" / "skill-registry.md"

def extract_skill_info(skill_dir: Path) -> dict:
    """Extract skill name and description from SKILL.md"""
    skill_md = skill_dir / "SKILL.md"
    if not skill_md.exists():
        return None
    
    try:
        content = skill_md.read_text(encoding="utf-8")
        
        # Extract name from first heading or frontmatter
        name = skill_dir.name
        
        # Extract description from first paragraph or trigger line
        description = ""
        for line in content.split("\n"):
            line = line.strip()
            if line.startswith("# "):
                name = line[2:].strip()
            elif line.startswith("description:"):
                description = line[12:].strip().strip('"')
            elif line.startswith("TRIGGER:") or line.startswith("Trigger:"):
                description = line
                break
            elif not description and len(line) > 20 and not line.startswith(("```", "---", "|")):
                description = line
        
        # Determine scope
        scope = "project" if "01_Personal_Os" in str(skill_dir) else "user"
        
        return {
            "name": name,
            "description": description[:200] if description else "—",
            "scope": scope,
            "path": str(skill_md).replace("\\", "/")
        }
    except Exception as e:
        print(f"Error reading {skill_md}: {e}")
        return None

def scan_local_skills() -> list:
    """Scan local OS skills directory"""
    skills = []
    seen_paths = set()
    
    if not LOCAL_SKILLS_DIR.exists():
        print(f"Local skills directory not found: {LOCAL_SKILLS_DIR}")
        return skills
    
    for skill_dir in LOCAL_SKILLS_DIR.rglob("*"):
        if skill_dir.is_dir() and (skill_dir / "SKILL.md").exists():
            skill_md_path = str(skill_dir / "SKILL.md").replace("\\", "/")
            
            # Skip if we've already seen this exact path
            if skill_md_path in seen_paths:
                continue
            seen_paths.add(skill_md_path)
            
            info = extract_skill_info(skill_dir)
            if info:
                skills.append(info)
    
    return skills

def parse_existing_registry() -> list:
    """Parse existing registry to get external skills"""
    if not REGISTRY_FILE.exists():
        return []
    
    skills = []
    content = REGISTRY_FILE.read_text(encoding="utf-8")
    
    # Parse table rows
    for line in content.split("\n"):
        if line.startswith("| `") and "` |" in line:
            parts = line.split("|")
            if len(parts) >= 5:
                name = parts[1].strip().strip("`")
                description = parts[2].strip()
                scope = parts[3].strip()
                path = parts[4].strip().strip("`")
                
                skills.append({
                    "name": name,
                    "description": description,
                    "scope": scope,
                    "path": path
                })
    
    return skills

def generate_registry(external_skills: list, local_skills: list) -> str:
    """Generate unified registry markdown"""
    all_skills = external_skills + local_skills
    
    # Deduplicate by path (keep first occurrence)
    seen_paths = set()
    seen_names = set()
    unique_skills = []
    duplicates_by_path = 0
    duplicates_by_name = 0
    
    for skill in all_skills:
        path = skill["path"]
        name = skill["name"].lower().strip()
        
        # Skip if we've already seen this path
        if path in seen_paths:
            duplicates_by_path += 1
            continue
        seen_paths.add(path)
        
        # Skip if we've already seen this name (case-insensitive)
        if name in seen_names:
            duplicates_by_name += 1
            continue
        seen_names.add(name)
        
        unique_skills.append(skill)
    
    unique_skills.sort(key=lambda x: x["name"].lower())
    
    lines = [
        "# Skill Registry — Think_Different",
        "",
        "<!-- Auto-generated by merge_skill_registry.py -->",
        f"Last updated: {datetime.now().strftime('%Y-%m-%d')}",
        "",
        "## Sources scanned",
        "",
        "- External skills (gentle-ai registry)",
        "- Local OS skills (01_Personal_Os/01_Core/02_Tools/02_Skills/)",
        "",
        "## Contract",
        "",
        "**Delegator use only.** This registry is an index, not a summary. Any agent that launches subagents reads it to select relevant skills, then passes exact `SKILL.md` paths for the subagent to read before work.",
        "",
        "`SKILL.md` remains the source of truth. Do not inject generated summaries or compact rules by default; pass paths so subagents load the full runtime contract and preserve author intent.",
        "",
        "## Skills",
        "",
        "| Skill | Trigger / description | Scope | Path |",
        "| --- | --- | --- | --- |",
    ]
    
    for skill in unique_skills:
        lines.append(f"| `{skill['name']}` | {skill['description']} | {skill['scope']} | `{skill['path']}` |")
    
    lines.append("")
    lines.append(f"**Total: {len(unique_skills)} skills** ({len(external_skills)} external + {len(local_skills)} local, {duplicates_by_path + duplicates_by_name} duplicates removed)")
    lines.append("")
    
    return "\n".join(lines), len(unique_skills), duplicates_by_path + duplicates_by_name

def main():
    print("Scanning external skills from existing registry...")
    external_skills = parse_existing_registry()
    print(f"  Found {len(external_skills)} external skills")
    
    print("Scanning local OS skills...")
    local_skills = scan_local_skills()
    print(f"  Found {len(local_skills)} local skills")
    
    print("Generating unified registry...")
    registry_content, unique_count, dup_count = generate_registry(external_skills, local_skills)
    
    print(f"Writing to {REGISTRY_FILE}...")
    REGISTRY_FILE.write_text(registry_content, encoding="utf-8")
    
    print(f"[OK] Done! Total: {unique_count} unique skills ({dup_count} duplicates removed)")

if __name__ == "__main__":
    main()
