#!/usr/bin/env python3
"""
Pattern Aggregator — Tracks pattern occurrences for playbook generation.
Part of Auto-Improvement ↔ Capital Token integration.
"""

import json
from datetime import datetime, timedelta
from pathlib import Path

def _find_repo_root() -> Path:
    """Find repo root by walking up until sentinel '00_Winter_is_Coming' is found."""
    for parent in Path(__file__).resolve().parents:
        if (parent / "00_Winter_is_Coming").exists():
            return parent
    raise RuntimeError("Could not find repo root — sentinel '00_Winter_is_Coming' not found")


PROJECT_ROOT = _find_repo_root()
AGGREGATOR_FILE = Path(__file__).parent / "pattern_aggregator.json"
AUTO_PLAYBOOKS_DIR = PROJECT_ROOT / "01_Personal_Os" / "02_Knowledge" / "10_Shared_Org" / "playbooks" / "auto-generated"

PATTERN_THRESHOLD = 3  # occurrences before generating playbook


def load_aggregator() -> dict:
    """Load pattern aggregator"""
    if AGGREGATOR_FILE.exists():
        try:
            return json.loads(AGGREGATOR_FILE.read_text(encoding="utf-8"))
        except Exception:
            pass
    return {"version": "1.0", "patterns": [], "last_updated": None}


def save_aggregator(data: dict):
    """Save pattern aggregator"""
    data["last_updated"] = datetime.now().isoformat()
    AGGREGATOR_FILE.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")


def record_pattern(pattern_hash: str, description: str, severity: str, category: str, fix: str = ""):
    """Record a pattern occurrence"""
    data = load_aggregator()
    patterns = data.get("patterns", [])

    # Find existing pattern
    existing = None
    for p in patterns:
        if p.get("hash") == pattern_hash:
            existing = p
            break

    if existing:
        existing["occurrences"] = existing.get("occurrences", 0) + 1
        existing["last_seen"] = datetime.now().isoformat()
        if fix:
            existing["suggested_fix"] = fix
    else:
        patterns.append({
            "hash": pattern_hash,
            "description": description,
            "severity": severity,
            "category": category,
            "occurrences": 1,
            "first_seen": datetime.now().isoformat(),
            "last_seen": datetime.now().isoformat(),
            "suggested_fix": fix,
            "playbook_generated": False
        })

    data["patterns"] = patterns
    save_aggregator(data)

    # Check threshold
    if existing and existing["occurrences"] >= PATTERN_THRESHOLD and not existing.get("playbook_generated"):
        generate_playbook_draft(existing)
        existing["playbook_generated"] = True
        save_aggregator(data)
        return True  # Playbook generated

    return False


def generate_playbook_draft(pattern: dict):
    """Generate a playbook draft from a recurring pattern"""
    AUTO_PLAYBOOKS_DIR.mkdir(parents=True, exist_ok=True)

    slug = pattern["description"][:50].lower().replace(" ", "-").replace("/", "-")
    filename = AUTO_PLAYBOOKS_DIR / f"auto-{slug}.md"

    content = f"""---
title: "Auto-Generated: {pattern['description']}"
version: 1.0
owner: "auto-generated"
status: "DRAFT — requires human review"
created: "{datetime.now().strftime('%Y-%m-%d')}"
pattern_hash: "{pattern['hash']}"
occurrences: {pattern['occurrences']}
tags: [auto-generated, {pattern.get('category', 'general')}]
---

# {pattern['description']}

> **WARNING:** This playbook was auto-generated by the Auto-Improvement engine.
> It is a DRAFT and requires human review before use.

## Pattern Details

- **Severity:** {pattern.get('severity', 'MEDIUM')}
- **Category:** {pattern.get('category', 'general')}
- **Occurrences:** {pattern.get('occurrences', 0)}
- **First Seen:** {pattern.get('first_seen', 'unknown')}
- **Last Seen:** {pattern.get('last_seen', 'unknown')}

## Description

{pattern['description']}

## Suggested Fix

{pattern.get('suggested_fix', 'No fix suggested. Review and add manually.')}

## Quality Gates

- [ ] Human reviewed
- [ ] Fix verified
- [ ] Move to `10_Shared_Org/playbooks/` when ready

---

*Auto-generated by Auto-Improvement ↔ Capital Token Integration*
*Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}*
"""

    filename.write_text(content, encoding="utf-8")
    print(f"[AUTO-PLAYBOOK] Generated: {filename}")


def get_patterns_by_severity(severity: str) -> list:
    """Get all patterns of a given severity"""
    data = load_aggregator()
    return [p for p in data.get("patterns", []) if p.get("severity") == severity]


def get_pending_playbooks() -> list:
    """Get patterns that have reached threshold but playbook not yet generated"""
    data = load_aggregator()
    return [
        p for p in data.get("patterns", [])
        if p.get("occurrences", 0) >= PATTERN_THRESHOLD and not p.get("playbook_generated")
    ]


if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1 and sys.argv[1] == "stats":
        data = load_aggregator()
        patterns = data.get("patterns", [])
        print(f"Total patterns: {len(patterns)}")
        print(f"By severity:")
        for sev in ["HIGH", "MEDIUM", "LOW"]:
            count = len([p for p in patterns if p.get("severity") == sev])
            print(f"  {sev}: {count}")
        pending = get_pending_playbooks()
        print(f"Pending playbooks: {len(pending)}")
    else:
        print("Usage: python pattern_aggregator.py stats")